# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."filebox-file-code-box" = {
    image = "docker.son5mu.win/lanol/filecodebox:latest";
    volumes = [
      "filebox_fcb-data:/app/data:rw"
    ];
    ports = [
      "12345:12345/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=file-code-box"
      "--network=filebox_default"
    ];
  };
  systemd.services."docker-filebox-file-code-box" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-filebox_default.service"
      "docker-volume-filebox_fcb-data.service"
    ];
    requires = [
      "docker-network-filebox_default.service"
      "docker-volume-filebox_fcb-data.service"
    ];
    partOf = [
      "docker-compose-filebox-root.target"
    ];
    wantedBy = [
      "docker-compose-filebox-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-filebox_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f filebox_default";
    };
    script = ''
      docker network inspect filebox_default || docker network create filebox_default
    '';
    partOf = [ "docker-compose-filebox-root.target" ];
    wantedBy = [ "docker-compose-filebox-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-filebox_fcb-data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect filebox_fcb-data || docker volume create filebox_fcb-data
    '';
    partOf = [ "docker-compose-filebox-root.target" ];
    wantedBy = [ "docker-compose-filebox-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-filebox-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
