# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."reader" = {
    image = "hectorqin/reader";
    environment = {
      "READER_APP_CACHECHAPTERCONTENT" = "true";
      "READER_APP_SECURE" = "true";
      "READER_APP_SECUREKEY" = "gui159";
      "READER_APP_USERBOOKLIMIT" = "200";
      "READER_APP_USERLIMIT" = "5";
      "SPRING_PROFILES_ACTIVE" = "prod";
    };
    volumes = [
      "/home/reader/logs:/logs:rw"
      "/home/reader/storage:/storage:rw"
    ];
    ports = [
      "4396:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=reader"
      "--network=reader_share_net"
    ];
  };
  systemd.services."docker-reader" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-reader_share_net.service"
    ];
    requires = [
      "docker-network-reader_share_net.service"
    ];
    partOf = [
      "docker-compose-reader-root.target"
    ];
    wantedBy = [
      "docker-compose-reader-root.target"
    ];
  };
  virtualisation.oci-containers.containers."watchtower" = {
    image = "containrrr/watchtower";
    environment = {
      "TZ" = "Asia/Shanghai";
    };
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    cmd = [ "reader" "watchtower" "--cleanup" "--schedule" "0 0 4 * * *" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=watchtower"
      "--network=reader_share_net"
    ];
  };
  systemd.services."docker-watchtower" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-reader_share_net.service"
    ];
    requires = [
      "docker-network-reader_share_net.service"
    ];
    partOf = [
      "docker-compose-reader-root.target"
    ];
    wantedBy = [
      "docker-compose-reader-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-reader_share_net" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f reader_share_net";
    };
    script = ''
      docker network inspect reader_share_net || docker network create reader_share_net --driver=bridge
    '';
    partOf = [ "docker-compose-reader-root.target" ];
    wantedBy = [ "docker-compose-reader-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-reader-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
