# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."mosdns" = {
    image = "docker.son5mu.win/irinesistiana/mosdns:v4.5.3";
    volumes = [
      "/etc/mosdns:/etc/mosdns:rw"
    ];
    ports = [
      "5454:53/udp"
      "5454:53/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mosdns"
      "--network=mosdns_default"
    ];
  };
  systemd.services."docker-mosdns" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-mosdns_default.service"
    ];
    requires = [
      "docker-network-mosdns_default.service"
    ];
    partOf = [
      "docker-compose-mosdns-root.target"
    ];
    wantedBy = [
      "docker-compose-mosdns-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-mosdns_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f mosdns_default";
    };
    script = ''
      docker network inspect mosdns_default || docker network create mosdns_default
    '';
    partOf = [ "docker-compose-mosdns-root.target" ];
    wantedBy = [ "docker-compose-mosdns-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-mosdns-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
