# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."momwechat-mom" = {
    image = "compose2nix/momwechat-mom";
    volumes = [
      "/root/nixos-config/docker/momWechat/nginx.conf:/etc/nginx/nginx.conf:rw"
    ];
    ports = [
      "4928:80/tcp"
    ];
    cmd = [ "nginx" "-g" "daemon off;" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mom"
      "--network=momwechat_default"
    ];
  };
  systemd.services."docker-momwechat-mom" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-momwechat_default.service"
    ];
    requires = [
      "docker-network-momwechat_default.service"
    ];
    partOf = [
      "docker-compose-momwechat-root.target"
    ];
    wantedBy = [
      "docker-compose-momwechat-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-momwechat_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f momwechat_default";
    };
    script = ''
      docker network inspect momwechat_default || docker network create momwechat_default
    '';
    partOf = [ "docker-compose-momwechat-root.target" ];
    wantedBy = [ "docker-compose-momwechat-root.target" ];
  };

  # Builds
  systemd.services."docker-build-momwechat-mom" = {
    path = [ pkgs.docker pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /root/nixos-config/docker/momWechat
      docker build -t compose2nix/momwechat-mom .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-momwechat-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
