version: "3"

services:
  langbot:
    image: rockchin/langbot:latest
    container_name: langbot
    volumes:
      - /home/ming/langbot/data:/app/data
      - /home/ming/langbot/plugins:/app/plugins
    restart: on-failure
    ports:
      - 5300:5300  # 供 WebUI 使用
      - 2280-2290:2280-2290  # 供消息平台适配器方向连接
    # 根据具体环境配置网络
  napcat:
     environment:
         - NAPCAT_UID=1000
         - NAPCAT_GID=100
     ports:
         - 3000:3000
         - 3001:3001
         - 6099:6099
     volumes:
       - /home/ming/langbot/QQ:/app/.config/QQ
       - /home/ming/langbot/config:/app/napcat/config
     container_name: napcat
     restart: always
     image: mlikiowa/napcat-docker:latest
