# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."caddy" = {
    image = "caddy:latest";
    volumes = [
      "/root/nixos-config/docker/vaultwarden/Caddyfile:/etc/caddy/Caddyfile:rw"
    ];
    ports = [
      "443:443/tcp"
      "80:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=caddy"
      "--network=vaultwarden_net"
    ];
  };
  systemd.services."docker-caddy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-vaultwarden_net.service"
    ];
    requires = [
      "docker-network-vaultwarden_net.service"
    ];
    partOf = [
      "docker-compose-vaultwarden-root.target"
    ];
    wantedBy = [
      "docker-compose-vaultwarden-root.target"
    ];
  };
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = "vaultwarden/server:latest";
    environment = {
      "DOMAIN" = "https://bitwarden.son5mu.win";
      "ROCKET_PORT" = "8192";
    };
    volumes = [
      "/root/nixos-config/docker/vaultwarden/vw-data:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vaultwarden"
      "--network=vaultwarden_net"
    ];
  };
  systemd.services."docker-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-vaultwarden_net.service"
    ];
    requires = [
      "docker-network-vaultwarden_net.service"
    ];
    partOf = [
      "docker-compose-vaultwarden-root.target"
    ];
    wantedBy = [
      "docker-compose-vaultwarden-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-vaultwarden_net" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f vaultwarden_net";
    };
    script = ''
      docker network inspect vaultwarden_net || docker network create vaultwarden_net
    '';
    partOf = [ "docker-compose-vaultwarden-root.target" ];
    wantedBy = [ "docker-compose-vaultwarden-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vaultwarden-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
